# Generated by Django 5.1 on 2024-08-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCNO', models.CharField(max_length=150)),
                ('custstate', models.CharField(max_length=150)),
                ('custpin', models.CharField(max_length=120)),
                ('DPD', models.CharField(max_length=10)),
            ],
        ),
    ]
